### ISSUE TITLE
How to control my unmanned vehicle

### ISSUE THREAD

**Issue by RayTang88** [chen-judge/MapGPT#1]
Thank you for your wonderful work .

I have an unmanned vehicle with an RGB camera on it. The chassis can be controlled by linear velocity and angular velocity.
So I have two questions:
 1. How can I use the images taken by the camera on the vehicle to successfully run your code?
 2. How can I combine the output of the model with executable quantities such as linear velocity and angular velocity, rather than simply forward, backward, left, and right? Do you have any good ideas? 
 
Thanks again.

**Comment by chen-judge** [comment]
Thank you for your interest!

1. We capture images from the simulator, save them, and then input them into GPT for experiments. In your vehicle, you can also use such a similar way.
2. For low-level motion planning, you can refer to my recent work: [Affordances-Oriented Planning using Foundation Models for Continuous Vision-Language Navigation](https://arxiv.org/abs/2407.05890)

**Comment by RayTang88** [comment]
OK, thanks for your reply.
Does it mean that the model only needs RGB sequence as input and no other content is needed, such as MapGPT_72_scenes_processed.json?
I will try your suggestion.thanks again！

**Comment by chen-judge** [comment]
Yes, this JSON file includes some instructions and ground truth related to VLN task.
