### ISSUE TITLE
Question about 'scan_data_dir'

### ISSUE THREAD

**Issue by madeline-past** [chen-judge/MapGPT#11]
hi dear author,I have a question about 'scan_data_dir'
```
if scan_data_dir:
    sim.setDatasetPath(scan_data_dir)
```
```
args.scan_data_dir = os.path.join(ROOTDIR, 'Matterport3D', 'v1_unzip_scans')
```
What should be put in ../dataset/Matterport3D/v1_unzip_scans?Is it the RGB_Observations.zip?

**Comment by chen-judge** [comment]
They are not images but simulator data. You need to install Matterport3D simulator first. Please follow this: [https://github.com/peteanderson80/Matterport3DSimulator](https://github.com/peteanderson80/Matterport3DSimulator)

**Comment by madeline-past** [comment]
Thanks a lot!
