### ISSUE TITLE
Environment conflict

### ISSUE THREAD

**Issue by madeline-past** [chen-judge/MapGPT#12]
Hi dear author,

I have to admit in advance that I am a green hand in configuring docker environment.So if I say something stupid,plz point out for me,thanks in advance!

Since [Matterport3DSimulator](https://github.com/peteanderson80/Matterport3DSimulator) is built from docker,then if we build the MapGPT in conda env like this:
```
conda create -n MapGPT python=3.10
conda activate MapGPT
pip install -r requirements.txt
```
The conda env will mask the docker environment,thus we are unable to import MatterSim inside conda env.

If anyone knows the answer,please point out for me,thanks in advance!

**Comment by chen-judge** [comment]
Sorry, I haven't tried using Docker to build MP3D, but installed it directly. Please refer to this [https://github.com/peteanderson80/Matterport3DSimulator?tab=readme-ov-file#building-without-docker](https://github.com/peteanderson80/Matterport3DSimulator?tab=readme-ov-file#building-without-docker)

**Comment by madeline-past** [comment]
I have tried installing MP3D directly but failed.I will try again later.Thanks anyway!
