### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by wlll123456** [chen-judge/MapGPT#4]
这是一个很好的工作，但是有一些疑问想请教一下
1.这个模型在训练和推理的整个流程中只使用了图片作为输入对吗？
2.这个Figure1中的图只是用来展示对吗？模型并不会将这种图以及3D场景作为输入对吧
![image](https://github.com/user-attachments/assets/9192f312-d491-4e50-9ef3-a32c141c260d)

**Comment by chen-judge** [comment]
谢谢你的关注。是的，文中的俯视图都是示意图来展示移动轨迹。
