### ISSUE TITLE
Run the experiments but accuracy dropped compared with the results on paper

### ISSUE THREAD

**Issue by ZoeyZheng0** [chen-judge/MapGPT#9]
Thank you for providing the detailed code :) I attempted to reproduce the results using the code provided. On GPT-4o, I achieved results similar to those reported in your repo, with only a ±1% variance. However, I observed a ~5% drop in SR and SPL when testing GPT-4v.

Below is a table with the results from my two test runs using your code:
<img width="588" alt="Screenshot 2024-10-31 at 12 37 26 PM" src="https://github.com/user-attachments/assets/ff65f1d3-8c47-4448-8465-0674f65cc01e">

I use the latest code of MapGPT and Matterport3D simulator. Also, install the same version packages in the requirements.txt file. Any insights into this variance would be greatly appreciated!

**Comment by chen-judge** [comment]
The results I reported are based on gpt-4-vision-preview, which is a preview version and may not be as stable. OpenAI may be continuously adjusting it. I have also heard that other versions of GPT have experienced similar issues (getting stupider and stupider). Therefore, I would recommend using GPT-4o directly, as you mentioned, as it can provide relatively stable and good results.

**Comment by xiyuying** [comment]
@ZoeyZheng0 
Hello, may I ask how to set the path for `--img_root`? What content does it include?
